### PR TITLE
Reconstructed NavBar to be responsive

### PR DESCRIPTION
**Pull request by riyasavant**
The NavBar was minimally styled in the previous version. Reconstructed to add a Brand name, push links to the right. The components are more structured, with the dark theme state being passed on as props, instead of having a button in the App component. This also attempts to solve issue #16

### CODE REVIEW

**Comment by riyasavant** [comment]
Screenshot (344)
Screenshot (345)

**Comment by riyasavant** [comment]
The NavBar was weirdly structured earlier, necessary changes can be made as required to this one.

**Comment by riyasavant** [comment]
@CapTen101  It's killing me, I will remember about this next time. Could the changes be merged without squashing?

**Comment by CapTen101** [comment]
@riyasavant I knew this would happen. Beginners often struggle hard with `rebase` command. I can still merge it though, since you've given very relevant names to the commits.
Still, I would recommend you to learn `rebase` as soon as you can 'cause it has some really cool benefits which will surely help you whenever you mess up your PRs, like playing around with commits etc..

**Comment by CapTen101** [comment]
PS. Always proceed with caution with `rebase`. It can make or break your PR/contribution :stuck_out_tongue:
I've had my fair share of issues with `rebase` in the past

**Comment by riyasavant** [comment]
@CapTen101 Yes will definitely consider learning it soon, Thanks for the suggestion though. I surely know who to ping if I get a rebase error xD

**Comment by CapTen101** [comment]
:eyes: Right. Yep, cool then!
I'll merge it.
@riyasavant

**Pull request merged**
